id: params
type: datasource
subtype: JavascriptQuery
resourceName: JavascriptQuery
template:
  ordered:
    - query: return null
    - evalType: script
createdAt: 2025-04-04T15:21:29.930Z
blockData:
  top: 48
  left: 48
  uuid: a764afd7-ee76-4587-b560-f3c2e96a0d04
  options: {}
  pluginId: params
  blockType: webhook
  editorType: JavascriptQuery
  isMinimized: false
  resourceName: webhook
  incomingOnSuccessEdges: []
